### ISSUE TITLE
What on earth do you want?!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by TKanX** [sammorozov/sammorozov#8]
Why did you do this? Please contact me

**Comment by Kinslayer47** [comment]
bro needs to stop following random people using a script.

**Comment by TKanX** [comment]
I have flashed my computer, and then used a password manager to reset the passwords for all accounts into random strong passwords.

**Comment by Kinslayer47** [comment]
Bro, he will still leak your information, but more power to you bro for upping your cybersecurity bro.
